# Generated by Django 5.2.6 on 2025-09-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_alter_menu_options_alter_menu_group_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='group_name',
        ),
    ]
